### ISSUE TITLE
Duplicate Displays on Reinstall

### ISSUE THREAD

**Issue by HornetXR5** [VirtualDisplay/Virtual-Display-Driver#148] opened 2024-08-31 02:40 UTC
Hi,

On uninstalling and reinstalling the driver, it creates duplicate displays. I cannot delete these. There was a similar issue posted however user could just remove from device manager to resolve the issue. This does not work for me and they reappear on reboot

**Comment by HornetXR5** [comment] 2024-08-31 02:40
REPOST OF CONTENTS OF PREVIOUSLY CLOSED ISSUE


> After the first uninstall, and reinstall, I found there are two virtual displays created... And I am unable to remove the driver.
> 
> ```powershell
> pnputil /delete-driver oem90.inf
> Microsoft PnP Utility
> 
> Failed to delete driver package: One or more devices are presently installed using the specified INF.
> ```
> 
> To remove all these displays, I have to force uninstall the driver via:
> 
> ```powershell
> pnputil /delete-driver oem90.inf /force /uninstall
> ```
> 
> and it worked.
> 
> However, any reinstall adds one more display to my system... and this is the third reinstall
> 
> ![image](https://private-user-images.githubusercontent.com/38860226/362800764-13bcf1dd-e818-4253-9665-c873a2dfa79d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNzIwNTgsIm5iZiI6MTcyNTA3MTc1OCwicGF0aCI6Ii8zODg2MDIyNi8zNjI4MDA3NjQtMTNiY2YxZGQtZTgxOC00MjUzLTk2NjUtYzg3M2EyZGZhNzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDAyMzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYTQzY2I3MmFkYTg5MDE0OGFjOWFkNWM1N2VmMGU4YWQ3YzY4ZmJmMTVlMjU4ZTI4MjQ2N2I0YzZjYzAyNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7xCDDDMh9gO8nZfiI1wb8MJA0iNlM_l7awcqof38Mf8) ![image](https://private-user-images.githubusercontent.com/38860226/362800807-60f48627-50da-44f9-92e8-0b93112b96d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNzIwNTgsIm5iZiI6MTcyNTA3MTc1OCwicGF0aCI6Ii8zODg2MDIyNi8zNjI4MDA4MDctNjBmNDg2MjctNTBkYS00NGY5LTkyZTgtMGI5MzExMmI5NmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDAyMzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMWY4ZjA1MjhmMGU2M2Y1NDhkODhkMTg3MDVmZWQ1MGI2NmMwNzY2ZmQyOTA0ZWQ1MDQzNmY4MDQwY2FhMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qg0u793iQTJOxEdJx44JCKf6PbTppJRNu6Qjt4rgNq8)

**Comment by HornetXR5** [comment] 2024-08-31 02:49
I'm sorry, what a time waste. It did not occur to me to try the uninstall in safe mode and that fixed it.

**Comment by zjoasan** [comment] 2024-08-31 08:47
> I'm sorry, what a time waste. It did not occur to me to try the uninstall in safe mode and that fixed it.

Thanks for the feedback.

**Comment by bud3699** [comment] 2024-09-04 06:41
I know this topic has already been resolved, however it think you're mistaken between uninstalling the driver compared to the device. Safe mode allows for uninstalling driver and the device doesn't start. Uninstalling the device and ticking removing driver, should be sufficient enough. I may be mistaken here as it's hard to diagnose an accurate cause without having the device on hand. But as jocke mentioned, your feedback is appreciated

**Comment by HornetXR5** [comment] 2024-09-04 06:50
> I know this topic has already been resolved, however it think you're mistaken between uninstalling the driver compared to the device. Safe mode allows for uninstalling driver and the device doesn't start. Uninstalling the device and ticking removing driver, should be sufficient enough. I may be mistaken here as it's hard to diagnose an accurate cause without having the device on hand. But as jocke mentioned, your feedback is appreciated

Hey, yeah perhaps. I chose "uninstall device" from device manager but it kept coming back. I don't think anything I did would stop the virtual monitors reappearing in both device manager and/or as actual virtual displays for us. Any reboot and they were back. Forcing uninstall of the driver did ultimately remove the device from device manager (though there were some hoops there too as access was denied etc), but ultimately on reinstall of the driver then it created multiple virtual monitors under device manager.

So I guess I perhaps had some terms mixed up, but ultimately there was duplicate devices and after removal and a fresh install of the drivers, multiple devices/virtual displays were created (despite this outcome not being supposed to happen). The additional devices/virtual displays could only be removed from device manager whilst in safe mode. 

I hope that helps.

**Comment by bud3699** [comment] 2024-09-04 06:59
Were you uninstalling the displays themselves or the display adapter?

**Comment by HornetXR5** [comment] 2024-09-04 07:10
> Were you uninstalling the displays themselves or the display adapter?

I don't have an answer to this as I don't actually understand the question - Within device manager i selected "uninstall device". That did not work as expected. I don't know if you would consider that the display or the display adapter. To me there's only 2 things I can remove; Drivers or Device. 

I also uninstalled the drivers completely. That removed everything as expected. No virtual displays could exist because there were no drivers. When i installed the drivers again however, it then created an additional display. Each time i removed and installed drivers it would always add another again i.e. n+1. First install there was 1 driver. 2nd install there was 2, 3rd install there was 3 etc, which I would not expect given the drivers were uninstalled prior to any reinstallation.

**Comment by bud3699** [comment] 2024-09-04 07:13
Then in this case I believe it to be the display you tried to uninstall, forcing the driver to be uninstalled would render the display adapter device unusable hence no monitors until attempt to reinstall, installing the driver and device again causing two display adapters to be created.


(The display adapter is a device which requires the driver and the display is created by the driver - this also shows in device manager)

**Comment by HornetXR5** [comment] 2024-09-05 01:44
> Then in this case I believe it to be the display you tried to uninstall, forcing the driver to be uninstalled would render the display adapter device unusable hence no monitors until attempt to reinstall, installing the driver and device again causing two display adapters to be created.
> 
> (The display adapter is a device which requires the driver and the display is created by the driver - this also shows in device manager)

Got you. Not sure if it should show or not, but only the Displays show in device manager and not the display adapter from what I could see.

That being said, it sounds like there's perhaps another issue that exists, being that on removal of the driver the display adapter should also be removed, but isn't? Perhaps that's what leads to there being multiple virtual displays being listed/installed on any further installs

**Comment by bud3699** [comment] 2024-09-05 01:58
> Got you. Not sure if it should show or not, but only the Displays show in device manager and not the display adapter from what I could see.
> 
> 
> 
> That being said, it sounds like there's perhaps another issue that exists, being that on removal of the driver the display adapter should also be removed, but isn't? Perhaps that's what leads to there being multiple virtual displays being listed/installed on any further installs


It is impossible for the displays to show but not the adapter, the adapter creates the displays. And that's not an issue either you can't remove the display and that remove the adapter. The display is created by the adapter it's impossible to remove the adapter on display removal. And I've already explained what the cause of the multiple virtual displays are

**Comment by auravan** [comment] 2024-09-09 03:01
same problem.i guess(just guess) the promble is about the 3rd step here
![image](https://github.com/user-attachments/assets/d920856f-a51c-4e0a-b9f8-4146f7540225)
i think we should fix this bug by figuring out how to delete the former file that was created when run this bat again.

**Comment by HornetXR5** [comment] 2024-09-09 03:21
> same problem.i guess(just guess) the promble is about the 3rd step here ![image](https://private-user-images.githubusercontent.com/73768105/365498798-d920856f-a51c-4e0a-b9f8-4146f7540225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTIzMTcsIm5iZiI6MTcyNTg1MjAxNywicGF0aCI6Ii83Mzc2ODEwNS8zNjU0OTg3OTgtZDkyMDg1NmYtYTUxYy00ZTBhLWI5ZjgtNDE0NmY3NTQwMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzMjAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZjM2OTRhODVjYzE1Y2M5M2MxZTc1YzYzN2IyOTZmNWRkZTY1MjIzNWM3ZGUxN2YzMDI5ZjllZDc4YmRlY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qZw1bvjq3ZsM3pfW37KqzvFrgpFJvugeVwe56B73YE4) i think we should fix this bug by figuring out how to delete the former file that was created when run this bat again.

Not sure if it helps but i never ran that .bat file after the initial install (so never ran it again on subsequent installs)

**Comment by auravan** [comment] 2024-09-09 03:34
I guess i know the how the problem happend:
you should just need to informed people how not just move the txt file that you mentioned.
![image](https://github.com/user-attachments/assets/3dc29b17-56cc-44c4-938f-603de7e63fe0)
just literally let people just move the whole IddSampleDriver to the path "C:\IddSampleDriver",or it would be like this
![image](https://github.com/user-attachments/assets/7a31ec87-20d9-4847-8cae-afed096cdade)

**Comment by bud3699** [comment] 2024-09-09 04:31
I would like to make some key points here, when reinstalling the device, you DO NOT need to install the bat file again, this is the cert file, if the cert is already there you DO NOT need it again

When uninstalling the device, DO NOT uninstall the device under MONITORS, uninstall the device under DISPLAY ADAPTERS

The display adapter installed CREATES a monitor on the monitor section, if you remove this monitor, the adapter still stays there, so will continue to function as normal on device restart

You CAN copy the entire folder to your C Drive and set up there, that's why the folder is shipped with the same name that is used

**Comment by itsmikethetech** [comment] 2024-12-09 14:31
It also seems like you have multipke Idd based drivers installed at once. I don't believe this is an issue with the driver itself. Closing for now as it's a bit old, but feel free to update if you have more info.

**Closed by itsmikethetech** 2024-12-09 14:31 UTC
Labels: help wanted, invalid
